### ISSUE TITLE
Добавить README.md

### ISSUE THREAD

**Issue by olegpolyakov** [a84277755/codedojo#1]
В файле укажи название проекта и короткое описание.

**Comment by olegpolyakov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Добавить README.md](https://trello.com/c/FkmPk8zw/1-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-readmemd)

**Comment by a84277755** [comment]
Добавил

**Comment by olegpolyakov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Выполнить ДЗ №1](https://trello.com/c/VQcnU3Mx/2-%D0%B2%D1%8B%D0%BF%D0%BE%D0%BB%D0%BD%D0%B8%D1%82%D1%8C-%D0%B4%D0%B7-%E2%84%961)
